name: Simple Addition

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - name: Run simple addition
        run: |
          python -c "print('1 + 1 + 1 =', 1+1+1)"
